### ISSUE TITLE
return no nodes and connections

### ISSUE THREAD

**Issue by chinajuanbob** [nghialv/promviz#16]
When query to prometheus` /api/v1/query?query=rate(gin_requests_total[1m])`, it returns

```
{
    "status": "success",
    "data": {
        "resultType": "vector",
        "result": [
            {
                "metric": {
                    "client": "172.17.0.1",
                    "code": "200",
                    "server": "172.17.0.23",
                    ...
                },
                "value": [
                    1539238433.351,
                    "0.0909090909090909"
                ]
            },
            ...
         ]
     }
}
```

The  `promviz.yaml` is
```
    graphName: Demo

    clusterLevel:
      - cluster: demo-cluster-1
        maxVolume: 40000
        serviceConnections:
          - query: rate(gin_requests_total[1m])
            prometheusURL: http://prometheus:9090
            source:
              label: client
            target:
              label: server
            status:
              label: code
              warningRegex: ^4..$
              dangerRegex: ^5..$
```

and promviz return no nodes and connections:

```
{
    "renderer": "global",
    "name": "Demo",
    "serverUpdateTime": 1539238330,
    "nodes": [],
    "connections": [],
    "classes": [
        {
            "name": "default",
            "color": "rgb(186, 213, 237)"
        }
    ]
}
```

What's wrong with my configurations? Thanks a lot!
